// src/store/tripActions.js

export const ACTIONS = {
  SET_PREFERENCES: 'SET_PREFERENCES',
  START_GENERATING: 'START_GENERATING',
  SET_ITINERARY: 'SET_ITINERARY',
  SET_WEATHER: 'SET_WEATHER',
  ADD_ALERT: 'ADD_ALERT',
  DISMISS_ALERT: 'DISMISS_ALERT',
  START_REPLANNING: 'START_REPLANNING',
  APPLY_REPLAN: 'APPLY_REPLAN',
  PROPOSE_REPLAN: 'PROPOSE_REPLAN',
  DISCARD_REPLAN: 'DISCARD_REPLAN',
  SET_ERROR: 'SET_ERROR',
  RESET: 'RESET',
  CLEAR_ALERTS: 'CLEAR_ALERTS', // Added to fix E-3
};
